### ISSUE TITLE
Provide project page contents

### ISSUE THREAD

**Issue by jgadsden** [OWASP/www-project-developer-guide#1]
This OWASP Project page needs contents provided, based on the readme from the  project repo at https://github.com/OWASP/DevGuide

**Comment by jgadsden** [comment]
@bradchesney79 and @hblankenship - I do not mind starting this project page, similarly to the ones I have already done:

- github.com/OWASP/www-project-secure-coding-practices-quick-reference-guide
- github.com/OWASP/www-project-threat-dragon

Brad has provided the content at [README.md](https://github.com/OWASP/DevGuide/blob/master/README.md), so most of this is cut and paste

**Comment by hblankenship** [comment]
We do have a couple of people who have already expressed interest in reviving this project. Let me discuss it with them and get back to you. The readme contents are already old and out of date as well.

**Comment by jgadsden** [comment]
@hblankenship has anybody been found to revive this project?
I would like to link over to it from the Secure Coding Practices Quick Reference Guide, and wanted to make sure that it was still a viable project

**Comment by hblankenship** [comment]
@jgadsden There are people who are interested but it hasn't gone anywhere. That said, there is no reason that, if you want, you could start up the project again and, if the people who are interested show up, then they can talk to you about co-leading. It's a project that I would like to get involved in myself, actually.  :) What do you think?

**Comment by jgadsden** [comment]
Sure @hblankenship , happy to help revive this project.

I am leading the Threat Dragon and Secure Coding Practices projects because we use these in the company I work for, and now our development teams could do with an up to date Developer Guide ... so I am not hungry for yet another project to lead on but I can help get it back up and see what interest that generates.
So if we are both co-leaders for a while then that sounds good, and if other leaders show up then I am happy to take a (very) back seat.

**Comment by hblankenship** [comment]
I will add you. I don't know if you noticed but the old document is in a 'sort of' ready state by going to https://owasp.org/www-project-developer-guide/current_release/

It was how far I got before getting busy. :p I will add you to the repo and re-ping another leader that was interested.

**Comment by jgadsden** [comment]
Looks good, thanks @hblankenship , I will make a start on the readme

**Comment by jgadsden** [comment]
updated index and added read me file, so can close this issue
