### ISSUE TITLE
Update: 09-training-education/02-webgoat

### ISSUE THREAD

**Issue by Linkxee-Tech** [OWASP/www-project-developer-guide#105]
**Describe what change you would like** :  

**Context** :  
Section: (eg '04-foundations/03-security-principles')

 

Please I try to install Webgoat in my system but it didn't work, how can I do to make it work please

**Comment by jgadsden** [comment]
Hello @Linkxee-Tech , I will have a look at installing it and will try to provide the content for this section

**Comment by jgadsden** [comment]
@Linkxee-Tech do you want to review what we have done? see if it helps you with WebGoat and edit as necessary
