### ISSUE TITLE
Issue: 09-training-education/09-secure-coding-dojo

### ISSUE THREAD

**Issue by WolfMan12333** [OWASP/www-project-developer-guide#145]
**Describe what change you would like** :  
Cloudflare 522 error for this website: https://securecodingdojo.owasp.org/

**Context** :  
Not sure who is responsible for this website: https://securecodingdojo.owasp.org/
but when I'm trying to load this website I'm getting an error which I mentioned at the beginning of this message. Not sure if you are able to help in this case

<img width="842" alt="error" src="https://github.com/OWASP/www-project-developer-guide/assets/1895944/17307638-7f6d-4476-b867-17499660cef0">

**Comment by jgadsden** [comment]
yes, I agree that this looks like a broken link at the moment
we have a github workflow that checks for broken links, and runs every day, which has not detected this as a broken link
it may be worth waiting a day to see if it comes back online

**Comment by WolfMan12333** [comment]
you know generally I didn't disturb busy people but I'm trying to get another badge there :D

**Comment by WolfMan12333** [comment]
Website loaded. What was the issue?

**Comment by jgadsden** [comment]
not sure why it was not accessible for a while, but [all good now](https://securecodingdojo.owasp.org/public/index.html)

**Comment by jgadsden** [comment]
closing as this is a duplicate of #147
