### ISSUE TITLE
Connection timed out - Error code 522

### ISSUE THREAD

**Issue by WolfMan12333** [OWASP/www-project-developer-guide#147]
Connection timed out - Error code 522

Hi, I wrote about this error code to someone I think here. It is happening when I want to connect to this website: https://securecodingdojo.owasp.org/

Will anyone help?

<img width="834" alt="Screenshot 2024-02-14 at 08 33 15" src="https://github.com/OWASP/www-project-developer-guide/assets/1895944/b6fdc583-ed1e-4c30-bbe9-d4a2273246db">

**Comment by jgadsden** [comment]
Hello @paul-ion , could you restart the site for us? Thanks

**Comment by jgadsden** [comment]
Hello @WolfMan12333 , the leader of the Secure Coding Dojo project ( @paul-ion ) has advised that this demonstration site is on a free tier of AWS and so the site can get overloaded - then needing a restart
It is one of those free services the open-source community provide that is 'best effort' but is not guaranteed
