### ISSUE TITLE
Create OpenAI Agent backed by this repo & the Wayfinder

### ISSUE THREAD

**Issue by alezza** [OWASP/www-project-developer-guide#196]
**Describe what content should be added** :  

Create an OpenAI chatbot backed by an OS LLM trained with the knowledge from this repo, the Wayfinder project (OWASP Integration Standards), SKF (?)

**Context** :  
All sections

**Comment by jgadsden** [comment]
after our discussions at Lisbon AppSec, is this something you can take on @alezza ?
I think Spyros Gasteratos was talking to us about linking in with OpenCRE, which has a similar chatbot?

**Comment by jgadsden** [comment]
Adding OpenCRE page to DevGuide, which links over to the integration standards project and can then be included in [OpenCRE Chat](https://www.opencre.org/chatbot)
