### ISSUE TITLE
Add OWASP MASWE

### ISSUE THREAD

**Issue by jgadsden** [OWASP/www-project-developer-guide#246]
**Describe what change you would like** :  
There is a new enumeration for the MAS project, [MASWE](https://mas.owasp.org/MASWE)
It would be good to provide a page on this

**Context** :  
Section: 07-implementation/04-maswe

**Comment by jgadsden** [comment]
@sushi2k or @cpholguera is this something you would like to add? I can create the work-in-progress file for it if you would like to provide content

**Comment by cpholguera** [comment]
@jgadsden absolutely. Feel free to suggest something and I'll be happy to review. Thanks so much for keeping an eye on our project!
