### ISSUE TITLE
ZAP is now Checkmarx

### ISSUE THREAD

**Issue by jgadsden** [OWASP/www-project-developer-guide#282]
**Describe what change you would like** :  
ZAP is now owned by Checkmarx and is in their portfolio, and we should not be seen to endorse one company's products and not another company's products. It is probably easier to remove the section on ZAP

See the [Checkmarx press release](https://checkmarx.com/press-releases/checkmarx-joins-forces-with-zap-to-supercharge-dynamic-application-security-testing-dast-for-the-enterprise-and-enhance-community-growth/) for what will be available to Checkmarx customers and what will remain available for the ZAP community

**Context** :  
Section: 08-verification/02-tools/01-zap.md

<img width="228" alt="Screenshot 2024-09-27 at 14 32 09" src="https://github.com/user-attachments/assets/da4fa795-81f3-4502-a414-0ad5fbefa7f5">

**Comment by sydseter** [comment]
Yes, these pages are wrong as well: https://owasp.org/www-project-devsecops-guideline/latest/02b-Dynamic-Application-Security-Testing

**Comment by sydseter** [comment]
https://github.com/OWASP/www-project-devsecops-guideline/issues/32

**Comment by sydseter** [comment]
There is a page at the www-community project that seems much more complete regarding DAST: https://owasp.org/www-community/Vulnerability_Scanning_Tools

**Comment by sydseter** [comment]
Perhaps there could be a page about DAST tools in general in stead?

**Comment by jgadsden** [comment]
yes, I agree @sydseter - do you want to write this or I can do it ? I am always happy for all contributions :)

**Comment by sydseter** [comment]
Ok, fine, challenge excepted.

**Comment by psiinon** [comment]
Paid for ZAP features? Thats news to me!
Checkmarx _do_ build a commercial product on top of ZAP, but so do lots of other companies: https://www.zaproxy.org/third-party-services/

Please check with the ZAP team before spreading disinformation.
ZAP is staying OSS, there will NOT be any paid for features in ZAP.

**Comment by sydseter** [comment]
It might be better to refer to a full list of tools instead of just the zap proxy since there are several owasp projects that strive to do DAST.

Good to see that the core of zap is going to remain free.

**Comment by psiinon** [comment]
That makes sence to me

**Comment by sydseter** [comment]
@jgadsden Should we close this and instead focus on what has been concluded?

**Comment by kingthorin** [comment]
> there are several owasp projects that strive to do DAST.

There are? Like what?

**Comment by sydseter** [comment]
I understood it like this:
ZAP is staying OSS, but due to there being several OWASP related tools that focus on DAST, instead of having a ZAP tools page, add a document describing DAST and a link to a list where you can pick and choose. Then, for the future, focus on giving some guidance on DAST as a tool.

**Comment by kingthorin** [comment]
> but due to there being several OWASP related tools that focus on DAST

That's news to me, what are these other OWASP DAST projects?

**Comment by psiinon** [comment]
TBH I'm not aware of any, or none that are active.
All of the OSS web scanners I know about are listed on https://github.com/psiinon/open-source-web-scanners
LMK if I'm missing any...

**Comment by sydseter** [comment]
Not scanners per-say, but there are several that use ZAP under the hood to achieve the same goal. Nice list @psiinon !

**Comment by sydseter** [comment]
I wouldn't doubt that even for a second.

**Comment by jgadsden** [comment]
@psiinon and @kingthorin , at the risk of incurring the Wrath of ZAP , I am only going by what the the Checkmarx press release says:

_Checkmarx customers will gain:_

_Enhanced engine development, ensuring that customers benefit from the most secure, optimized and up-to-date solutions. The combined team will expand and enhance ZAP with innovative new features so that it can be leveraged both alone and within Checkmarx DAST_

so that to me sounds like paid for features.

**Comment by kingthorin** [comment]
"...alone and within..."

Alone being ZAP OpenSource 👍

**Comment by sydseter** [comment]
If we look past that discussion. I am guessing the best documentation on ZAP will always be provided by zap, at any given time. And, given that we want to strive to be as agnostic as possible regarding the use of tools and technologies, perhaps there shouldn't be a individual page about zap anyway. Wouldn't a page on dast instead of zap anyway be an improvement?

**Comment by kingthorin** [comment]
> the best documentation on ZAP will always be provided by zap

Yes, in the vast majority of cases that should be true.

As for a generic page, yes that probably makes most sense for OWASP and this guide.

**Comment by jgadsden** [comment]
Yes, I agree that the Checkmarx press release clearly does state that paid for customers will get enhanced ZAP features not available to the ZAP community members, and that these new ZAP features will also be used in the existing Checkmarx DAST CxOne product
If this is not the case then it should be corrected by Checkmarx, but until then we have to take them at their word

It is not an easy decision to remove the ZAP section from the Developer Guide, after all we are all ZAP users to the core :)

**Comment by psiinon** [comment]
Those features will be in Checkmax DAST, which is a commercial tool built on top of ZAP.
Yes, we will almost certainly be involved in developing them.
They will not be commercial ZAP features.
Maybe the press release could have been clearer, but its a press release, its been released and so it will not be updated.
All of the ZAP project leaders are here on this ticket. We're all Checkmarx employees (or will be in one case).
We are telling you quite clearly that any commertial features built on top of ZAP will be in Checkmarx DAST and not in ZAP.

**Comment by jgadsden** [comment]
yes, apologies @thc202 I now see what you are saying - the issue description is misleading
I will alter it so that it is more clear
