### ISSUE TITLE
Update: 05-requirements/05-asvs

### ISSUE THREAD

**Issue by ethnh** [OWASP/www-project-developer-guide#309]
**Describe what change you would like** :  
On this page: https://owasp.org/www-project-developer-guide/draft/requirements/application_security_verification_standard/

It mentions SecurityRAT, but SecurityRAT looks like a tool out of 2016 that is not even used anymore? Potentially consider removing this link from the page? It confused me a lot

**Context** :  
Section: (eg '04-foundations/03-security-principles')

**Comment by jgadsden** [comment]
@ethnh the Security Rat tool is definitely maintained and updated, version 1.8.10 was release in July this year (2024) : https://github.com/SecurityRAT/SecurityRAT/releases/tag/v1.8.10
I agree the demo is lagging a bit at version 1.8.8 (version October 2023) : https://securityrat.org/login

**Comment by jgadsden** [comment]
Hope this answers the question @ethnh and we can npw close this issue

**Comment by ethnh** [comment]
Yep thx. sorry for the interruption. Take care of yourself.
