### ISSUE TITLE
provide a mascot / logo

### ISSUE THREAD

**Issue by jgadsden** [OWASP/www-project-developer-guide#4]
**Describe what change you would like**
It would be great to have a mascot image or a logo for the Developer Guide. It helps people to identify with the project and may encourage contributions

If we really really want, we could have a Developer Guide anthem as well - but that may be going too far ;)

**Context**
see [Threat Dragon cupcake](https://github.com/OWASP/www-project-threat-dragon/blob/main/assets/images/cupcake-256x256.png)

**Comment by hblankenship** [comment]
Guide could be some sort of dog or perhaps a wilderness guide type logo (compass, safari hat, crossed paddles?).... I could throw it to Hugo....

**Comment by jgadsden** [comment]
Yes, I love this logo - where shall we store it? I suggest `assets/images`
